# docker-compose.yml
version: "3.8"

services:
  glpi-db:
    image: docker.io/${DOCKERHUB_USERNAME}/glpi-db:latest
    container_name: glpi-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER:     ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - glpi_db_data:/var/lib/mysql

  glpi-app:
    image: docker.io/${DOCKERHUB_USERNAME}/glpi-app:latest
    container_name: glpi-app
    depends_on:
      - glpi-db
    ports:
      - "8080:80"           # http://localhost:8080 (o en tu VM:80 si lo reenvías así)
    volumes:
      - glpi_files:/var/www/html/glpi/files
    environment:
      GLPI_DB_HOST:     glpi-db
      GLPI_DB_NAME:     ${MYSQL_DATABASE}
      GLPI_DB_USER:     ${MYSQL_USER}
      GLPI_DB_PASSWORD: ${MYSQL_PASSWORD}

  glpi-bot:
    image: docker.io/${DOCKERHUB_USERNAME}/glpi-bot:latest
    container_name: glpi-bot
    restart: unless-stopped
    depends_on:
      - glpi-app
    ports:
      - "8000:8000"      # health-check y endpoint /ping
    environment:
      BOT_TOKEN:        ${BOT_TOKEN}
      GLPI_API_URL:     http://glpi-app/apirest.php
      GLPI_APP_TOKEN:   ${GLPI_APP_TOKEN}
      GLPI_USER_TOKEN:  ${GLPI_USER_TOKEN}

volumes:
  glpi_db_data:
  glpi_files:
  glpi_public:  # si lo activas en el futuro
