#version: "3.8"

services:
  glpi-db:
    image: ${REGISTRY:-docker.io}/${IMAGE_DB:-jyrodriguezg95/glpi-db}:latest
    container_name: glpi-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE:     ${MYSQL_DATABASE}
      MYSQL_USER:         ${MYSQL_USER}
      MYSQL_PASSWORD:     ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - glpi_db_data:/var/lib/mysql

  glpi-app:
    image: ${REGISTRY:-docker.io}/${IMAGE_APP:-jyrodriguezg95/glpi-app}:latest
    container_name: glpi-app
    restart: unless-stopped
    depends_on:
      - glpi-db
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - glpi_files:/var/www/html/glpi/files

  glpi-bot:
    image: ${REGISTRY:-docker.io}/${IMAGE_BOT:-jyrodriguezg95/glpi-bot}:latest
    container_name: glpi-bot
    restart: unless-stopped
    depends_on:
      - glpi-app
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  glpi_db_data:
  glpi_files: