#version: "3.8"

services:
  glpi-db:
    image: mariadb:lts
    container_name: glpi-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER:     ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - glpi_db_data:/var/lib/mysql
  #commit de pruebas 
  glpi-app:
    build:
      context: ./glpi-app        # carpeta donde está el código
      dockerfile: Dockerfile     # nombre del Dockerfile (por defecto)
    container_name: glpi-app
    depends_on:
      - glpi-db
    ports:
      - "8080:80"           # http://localhost:8080
    volumes:
      - glpi_files:/var/www/html/glpi/files
     # - glpi_public:/var/www/html/glpi/public        ### ← nuevo volumen para /public
     # - ./glpi-app/glpi.conf:/etc/nginx/conf.d/glpi.conf:ro ### ← monta tu glpi.conf endurecido
      
    environment:
      GLPI_DB_HOST:     glpi-db
      GLPI_DB_NAME:     ${MYSQL_DATABASE}
      GLPI_DB_USER:     ${MYSQL_USER}
      GLPI_DB_PASSWORD: ${MYSQL_PASSWORD}

  glpi-bot:
    build:
      context: ./glpi-bot          # directorio donde tienes el Dockerfile del bot
    container_name: glpi-bot
    restart: unless-stopped
    depends_on:
      - glpi-app
    environment:
      BOT_TOKEN:        ${BOT_TOKEN}
      GLPI_API_URL:     http://glpi-app/api
      GLPI_APP_TOKEN:   ${GLPI_APP_TOKEN}
      GLPI_USER_TOKEN:  ${GLPI_USER_TOKEN}
    ports:
      - "8000:8000"      # FastAPI / Webhook opcional

volumes:
  glpi_db_data:
  glpi_files:
  glpi_public:    